application: dashpyq
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /lib
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: handler.app
 
libraries:
- name: jinja2
  version: latest

error_handlers:
- file: /templates/default_error.html
